
issuerCreateSchema ( issuerDid, name, version, attrNames ) 
issuerCreateAndStoreCredentialDef ( wh, issuerDid, schema, tag, signatureType, config ) 
issuerCreateAndStoreRevocReg ( wh, issuerDid, revocDefType, tag, credDefId, config, tailsWriterHandle )
issuerCreateCredentialOffer ( wh, credDefId )
issuerCreateCredential ( wh, credOffer, credReq, credValues, revRegId, blobStorageReaderHandle )
issuerRevokeCredential ( wh, blobStorageReaderHandle, revRegId, credRevocId )
issuerMergeRevocationRegistryDeltas ( revRegDelta, otherRevRegDelta )
proverCreateMasterSecret ( wh, masterSecretId )
proverCreateCredentialReq ( wh, proverDid, credOffer, credDef, masterSecretId )
proverStoreCredential ( wh, credId, credReqMetadata, cred, credDef, revRegDef ) 
proverGetCredentials ( wh, filter )
proverGetCredential ( wh, credId )
proverSearchCredentials ( wh, query )
proverFetchCredentials ( sh, count ) 
proverCloseCredentialsSearch ( sh )
proverGetCredentialsForProofReq ( wh, proofRequest )
proverSearchCredentialsForProofReq ( wh, proofRequest, extraQuery ) 
proverFetchCredentialsForProofReq ( sh, itemReferent, count ) 
proverCloseCredentialsSearchForProofReq ( sh )
proverCreateProof ( wh, proofReq, requestedCredentials, masterSecretName, schemas, credentialDefs, revStates ) 
verifierVerifyProof ( proofRequest, proof, schemas, credentialDefsJsons, revRegDefs, revRegs )
createRevocationState ( blobStorageReaderHandle, revRegDef, revRegDelta, timestamp, credRevId )
updateRevocationState ( blobStorageReaderHandle, revState, revRegDef, revRegDelta, timestamp, credRevId )
